receivers:
  hostmetrics:
    root_path: /hostfs
    collection_interval: 30s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      disk:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      network:
      load:
      paging:
      processes:
  docker_stats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 30s

service:
  pipelines:
    metrics/host:
      receivers: [hostmetrics]
      processors: [memory_limiter, batch]
      exporters: [clickhouse]
    metrics/docker:
      receivers: [docker_stats]
      processors: [memory_limiter, batch]
      exporters: [clickhouse]

