name: deploy

on:
  push:
    branches: main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: pull
        working-directory: /www/clickstack/
        run: |
          git remote set-url origin https://github.com/Gratheon/clickstack.git
          git fetch origin main
          git reset --hard
          git clean -fd
          git reset --hard origin/main

      - name: restart
        working-directory: /www/clickstack/
        run: chmod +x restart.sh && ./restart.sh
